//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbayMVC.appharbor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblItem", Namespace="http://schemas.datacontract.org/2004/07/EbayFactory")]
    [System.SerializableAttribute()]
    public partial class tblItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gallery_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string listing_urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gallery_url {
            get {
                return this.gallery_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.gallery_urlField, value) != true)) {
                    this.gallery_urlField = value;
                    this.RaisePropertyChanged("gallery_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_category {
            get {
                return this.item_categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.item_categoryField, value) != true)) {
                    this.item_categoryField = value;
                    this.RaisePropertyChanged("item_category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_id {
            get {
                return this.item_idField;
            }
            set {
                if ((object.ReferenceEquals(this.item_idField, value) != true)) {
                    this.item_idField = value;
                    this.RaisePropertyChanged("item_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_title {
            get {
                return this.item_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.item_titleField, value) != true)) {
                    this.item_titleField = value;
                    this.RaisePropertyChanged("item_title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string listing_url {
            get {
                return this.listing_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.listing_urlField, value) != true)) {
                    this.listing_urlField = value;
                    this.RaisePropertyChanged("listing_url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cat_count", Namespace="http://schemas.datacontract.org/2004/07/EbayFactory")]
    [System.SerializableAttribute()]
    public partial class cat_count : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> category_countField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string category_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> category_count {
            get {
                return this.category_countField;
            }
            set {
                if ((this.category_countField.Equals(value) != true)) {
                    this.category_countField = value;
                    this.RaisePropertyChanged("category_count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category_id {
            get {
                return this.category_idField;
            }
            set {
                if ((object.ReferenceEquals(this.category_idField, value) != true)) {
                    this.category_idField = value;
                    this.RaisePropertyChanged("category_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="EbayClient", ConfigurationName="appharbor.IEbayClient")]
    public interface IEbayClient {
        
        [System.ServiceModel.OperationContractAttribute(Action="EbayClient/IEbayClientWrite/FindByCategory", ReplyAction="EbayClient/IEbayClientWrite/FindByCategoryResponse")]
        void FindByCategory(string[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="EbayClient/IEbayClientWrite/EbayTopLevelCategories", ReplyAction="EbayClient/IEbayClientWrite/EbayTopLevelCategoriesResponse")]
        void EbayTopLevelCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="EbayClient/IEbayClientWrite/CreateSiteDataBase", ReplyAction="EbayClient/IEbayClientWrite/CreateSiteDataBaseResponse")]
        void CreateSiteDataBase();
        
        [System.ServiceModel.OperationContractAttribute(Action="EbayClient/IEbayClientWrite/SetCategoryCount", ReplyAction="EbayClient/IEbayClientWrite/SetCategoryCountResponse")]
        void SetCategoryCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="EbayClient/IEbayClientRead/GetCategories", ReplyAction="EbayClient/IEbayClientRead/GetCategoriesResponse")]
        string[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="EbayClient/IEbayClientRead/ItemByCategory", ReplyAction="EbayClient/IEbayClientRead/ItemByCategoryResponse")]
        EbayMVC.appharbor.tblItem[] ItemByCategory(string cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="EbayClient/IEbayClientRead/TestConnection", ReplyAction="EbayClient/IEbayClientRead/TestConnectionResponse")]
        string TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="EbayClient/IEbayClientRead/GetCategoryCount", ReplyAction="EbayClient/IEbayClientRead/GetCategoryCountResponse")]
        EbayMVC.appharbor.cat_count[] GetCategoryCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="EbayClient/IEbayClientRead/FindByKeyWord", ReplyAction="EbayClient/IEbayClientRead/FindByKeyWordResponse")]
        EbayMVC.appharbor.tblItem[] FindByKeyWord(string items);
        
        [System.ServiceModel.OperationContractAttribute(Action="EbayClient/IEbayClientRead/GetLog", ReplyAction="EbayClient/IEbayClientRead/GetLogResponse")]
        string[] GetLog();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEbayClientChannel : EbayMVC.appharbor.IEbayClient, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EbayClientClient : System.ServiceModel.ClientBase<EbayMVC.appharbor.IEbayClient>, EbayMVC.appharbor.IEbayClient {
        
        public EbayClientClient() {
        }
        
        public EbayClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EbayClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EbayClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EbayClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void FindByCategory(string[] items) {
            base.Channel.FindByCategory(items);
        }
        
        public void EbayTopLevelCategories() {
            base.Channel.EbayTopLevelCategories();
        }
        
        public void CreateSiteDataBase() {
            base.Channel.CreateSiteDataBase();
        }
        
        public void SetCategoryCount() {
            base.Channel.SetCategoryCount();
        }
        
        public string[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public EbayMVC.appharbor.tblItem[] ItemByCategory(string cat) {
            return base.Channel.ItemByCategory(cat);
        }
        
        public string TestConnection() {
            return base.Channel.TestConnection();
        }
        
        public EbayMVC.appharbor.cat_count[] GetCategoryCount() {
            return base.Channel.GetCategoryCount();
        }
        
        public EbayMVC.appharbor.tblItem[] FindByKeyWord(string items) {
            return base.Channel.FindByKeyWord(items);
        }
        
        public string[] GetLog() {
            return base.Channel.GetLog();
        }
    }
}
